ref: /mmfs1/gscratch/stergachislab/assemblies/hg38.analysisSet.fa
ref_name: hg38
n_chunks: 200
max_t: 4
dhs: data/GM12878_DHS.bed.gz # can be anything if not traing a model
manifest: config/indata.tbl
#model: results/GM12878_v0.1.5/model.dat # if not provided will train a new model
# only used in model training
excludes:
  - data/hg38.blacklist.ENCFF356LFX.bed.gz
  - data/hg38.gap.bed
